### ISSUE TITLE
Use convention class instead of only defining the methods

### ISSUE THREAD

**Issue by tziemek** [artiso-solutions/adsd-hotel#31]
Default conventions won't be overwritten if we use a class deriving from `IMessageConvention`. See https://docs.particular.net/nservicebus/messaging/conventions

**Comment by tommasobertoni** [comment]
Do we want the default conventions? i.e. implementing `ICommand`, `IEvent`...
Name-conventions feel much lighter to me.

In any case, the change is minimal between custom conventions and `IMessageConvention`, so no big deal.

cc @artiso-solutions/systems-design

**Comment by tziemek** [comment]
With `IMessageConvention` we can more easily use both, because the default conventions don't get overwritten. I put that already in #13
